
apiVersion: v1
kind: Service
metadata:
  name: pbw
  labels:
    app: pbw
spec:
  ports:
    - port: 9080
  selector:
    app: pbw
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pbw
  name: pbw
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pbw
    spec:
      containers:
      - image: mycluster.icp:8500/default/pbw:latest
        name: pbw
        ports:
        - containerPort: 9080
          protocol: TCP
